export default [
  {
    ignores: ['node_modules/**', 'node_modules.nosync/**'],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        // Node.js
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        // Browser
        window: 'readonly',
        document: 'readonly',
        fetch: 'readonly',
        FormData: 'readonly',
        WebSocket: 'readonly',
        crypto: 'readonly',
        HTMLElement: 'readonly',
        HTMLVideoElement: 'readonly',
        HTMLInputElement: 'readonly',
        FileList: 'readonly',
        File: 'readonly',
        Event: 'readonly',
        MessageEvent: 'readonly',
        CloseEvent: 'readonly',
        Plyr: 'readonly',
        Sortable: 'readonly',
        tailwind: 'readonly',
        localStorage: 'readonly',
        matchMedia: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_' }],
      'no-undef': 'error',
      'no-const-assign': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-unreachable': 'warn',
      eqeqeq: ['warn', 'always'],
      'no-var': 'error',
      'prefer-const': 'warn',
    },
  },
];
